<?php
namespace Aspen\TrainingEntitlements;

defined( 'ABSPATH' ) || exit;

final class AdminController {
	private $batches; private $redemptions; private $audit; private $tokens;
	public function __construct( $b, $r, $a, $t ) { $this->batches=$b; $this->redemptions=$r; $this->audit=$a; $this->tokens=$t; }
	public function hooks() { add_action( 'admin_menu', array( $this, 'menu' ) ); add_action( 'admin_post_ate_batch_action', array( $this, 'action' ) ); }
	public function menu() { add_submenu_page( 'woocommerce', __( 'Training Entitlements', 'aspen-training-entitlements' ), __( 'Training Entitlements', 'aspen-training-entitlements' ), 'manage_woocommerce', 'ate-batches', array( $this, 'page' ) ); }
	public function page() { if ( ! current_user_can( 'manage_woocommerce' ) ) wp_die( esc_html__( 'Unauthorized.', 'aspen-training-entitlements' ) ); $id=isset($_GET['batch_id'])?absint($_GET['batch_id']):0; echo '<div class="wrap"><h1>' . esc_html__( 'Training Entitlements', 'aspen-training-entitlements' ) . '</h1>'; if ( $id ) $this->detail( $id ); else $this->list(); echo '</div>'; }
	private function list() { $filters=array(); foreach(array('status','course_id','customer_user_id','order_id','subscription_id') as $key) if(isset($_GET[$key])) $filters[$key]=sanitize_text_field(wp_unslash($_GET[$key])); echo '<form><input type="hidden" name="page" value="ate-batches"><select name="status"><option value="">All statuses</option>'; foreach(array('active','exhausted','expired','revoked') as $s) echo '<option ' . selected($filters['status']??'',$s,false) . '>' . esc_html($s) . '</option>'; echo '</select> <input name="order_id" placeholder="Order ID" value="' . esc_attr($filters['order_id']??'') . '"> <input name="subscription_id" placeholder="Subscription ID" value="' . esc_attr($filters['subscription_id']??'') . '"> <input name="customer_user_id" placeholder="Customer ID" value="' . esc_attr($filters['customer_user_id']??'') . '"> <button class="button">Filter</button></form><table class="widefat striped"><thead><tr><th>ID</th><th>Course</th><th>Customer</th><th>Order / Subscription</th><th>Used / Total</th><th>Expires</th><th>Status</th></tr></thead><tbody>'; foreach($this->batches->search($filters) as $b) echo '<tr><td><a href="' . esc_url(admin_url('admin.php?page=ate-batches&batch_id='.$b->id)) . '">#' . esc_html($b->id) . '</a></td><td>' . esc_html(get_the_title($b->course_id)) . '</td><td>' . esc_html($b->customer_user_id) . '</td><td>' . esc_html($b->order_id . ($b->subscription_id?' / '.$b->subscription_id:'')) . '</td><td>' . esc_html($b->entitlements_used.'/'.$b->entitlements_total) . '</td><td>' . esc_html(wp_date('Y-m-d H:i',strtotime($b->expires_at.' UTC'))) . '</td><td>' . esc_html($b->status) . '</td></tr>'; echo '</tbody></table>'; }
	private function detail( $id ) { $b=$this->batches->find($id); if(!$b){echo '<p>Not found.</p>';return;} $user=get_userdata($b->customer_user_id); echo '<h2>Batch #' . esc_html($b->id) . '</h2><p><strong>Purchaser:</strong> ' . esc_html($user?$user->display_name.' ('.$user->user_email.')':'Guest') . '<br><strong>Order:</strong> ' . esc_html($b->order_id) . '<br><strong>Subscription:</strong> ' . esc_html($b->subscription_id?:'—') . '<br><strong>Product / Variation:</strong> ' . esc_html($b->product_id.' / '.$b->variation_id) . '<br><strong>Course:</strong> ' . esc_html(get_the_title($b->course_id)) . '<br><strong>Seats:</strong> ' . esc_html($b->entitlements_used.'/'.$b->entitlements_total) . '<br><strong>Status:</strong> ' . esc_html($b->status) . '</p><form method="post" action="' . esc_url(admin_url('admin-post.php')) . '"><input type="hidden" name="action" value="ate_batch_action"><input type="hidden" name="batch_id" value="' . esc_attr($id) . '">'; wp_nonce_field('ate_batch_'.$id); echo '<select name="operation"><option value="revoke">Revoke</option><option value="reactivate">Reactivate</option><option value="regenerate">Regenerate token</option><option value="expiration">Change expiration</option><option value="total">Change total</option></select> <input name="value" placeholder="Value / YYYY-MM-DD HH:MM:SS"> <button class="button button-primary">Apply</button></form><h3>Redemptions</h3><table class="widefat"><tr><th>User</th><th>Name snapshot</th><th>Email snapshot</th><th>Redeemed</th></tr>'; foreach($this->redemptions->completed_for_batch($id) as $r) echo '<tr><td>' . esc_html($r->user_id) . '</td><td>' . esc_html(trim($r->first_name_snapshot.' '.$r->last_name_snapshot)) . '</td><td>' . esc_html($r->email_snapshot) . '</td><td>' . esc_html($r->redeemed_at) . '</td></tr>'; echo '</table><h3>Audit trail</h3><ul>'; foreach($this->audit->for_batch($id) as $a) echo '<li>' . esc_html($a->created_at.' — '.$a->action.' — user '.$a->actor_user_id) . '</li>'; echo '</ul>'; }
	public function action() { if(!current_user_can('manage_woocommerce')) wp_die('Unauthorized'); $id=absint($_POST['batch_id']??0); check_admin_referer('ate_batch_'.$id); $b=$this->batches->find($id); if(!$b) wp_die('Not found'); $op=sanitize_key($_POST['operation']??''); $value=sanitize_text_field(wp_unslash($_POST['value']??'')); if('revoke'===$op) $this->batches->update_admin($id,array('status'=>'revoked'),'batch_revoked'); elseif('reactivate'===$op && strtotime($b->expires_at.' UTC')>time() && $b->entitlements_used<$b->entitlements_total) $this->batches->update_admin($id,array('status'=>'active'),'batch_reactivated'); elseif('regenerate'===$op){$token=$this->batches->regenerate($id); if($token){$order=wc_get_order($b->order_id);$item=$order?$order->get_item($b->order_item_id):null;if($item){$item->update_meta_data('_ate_redemption_token',$token);$item->save();}}} elseif('expiration'===$op){$date=date_create_immutable($value,wp_timezone());if($date)$this->batches->update_admin($id,array('expires_at'=>get_gmt_from_date($date->format('Y-m-d H:i:s'))),'expiration_changed');} elseif('total'===$op && absint($value)>=$b->entitlements_used) $this->batches->update_admin($id,array('entitlements_total'=>absint($value),'status'=>absint($value)==$b->entitlements_used?'exhausted':$b->status),'entitlement_count_changed'); wp_safe_redirect(admin_url('admin.php?page=ate-batches&batch_id='.$id)); exit; }
}
