<?php
namespace Aspen\TrainingEntitlements;

defined( 'ABSPATH' ) || exit;

final class FrontendController {
	private $batches; private $redemptions; private $service; private $tokens; private $lifter;
	public function __construct( $b, $r, $s, $t, $l ) { $this->batches=$b; $this->redemptions=$r; $this->service=$s; $this->tokens=$t; $this->lifter=$l; }
	public function hooks() { add_action( 'init', array( $this, 'rewrites' ) ); add_filter( 'query_vars', function( $vars ){ $vars[]='ate_token'; return $vars; } ); add_action( 'template_redirect', array( $this, 'redeem_page' ) ); add_filter( 'woocommerce_account_menu_items', array( $this, 'menu' ) ); add_action( 'woocommerce_account_training-enrollments_endpoint', array( $this, 'account' ) ); }
	public function rewrites() { add_rewrite_rule( '^training/redeem/([A-Za-z0-9_-]+)/?$', 'index.php?ate_token=$matches[1]', 'top' ); add_rewrite_endpoint( 'training-enrollments', EP_ROOT | EP_PAGES ); }
	public function menu( $items ) { $logout=$items['customer-logout'] ?? null; unset( $items['customer-logout'] ); $items['training-enrollments']=__( 'Training Enrollments', 'aspen-training-entitlements' ); if ( $logout ) $items['customer-logout']=$logout; return $items; }
	private function state_message( $state ) { return array( 'invalid'=>__( 'This training invitation is invalid.', 'aspen-training-entitlements' ), 'expired'=>__( 'This training invitation has expired.', 'aspen-training-entitlements' ), 'revoked'=>__( 'This training invitation has been revoked.', 'aspen-training-entitlements' ), 'exhausted'=>__( 'No enrollments remain on this invitation.', 'aspen-training-entitlements' ), 'already_redeemed'=>__( 'You have already redeemed this invitation.', 'aspen-training-entitlements' ), 'already_enrolled'=>__( 'You are already enrolled in this course. No entitlement was used.', 'aspen-training-entitlements' ), 'course_missing'=>__( 'This course is no longer available.', 'aspen-training-entitlements' ), 'failed'=>__( 'Enrollment failed unexpectedly. No entitlement was consumed; please try again.', 'aspen-training-entitlements' ), 'success'=>__( 'Enrollment successful!', 'aspen-training-entitlements' ) )[ $state ] ?? ''; }
	public function redeem_page() {
		$token=get_query_var( 'ate_token' ); if ( ! $token ) return; $token=sanitize_text_field( $token ); $batch=$this->batches->find_by_token( $token ); $state=$batch ? '' : 'invalid';
		if ( $batch && 'revoked' === $batch->status ) $state='revoked'; elseif ( $batch && strtotime( $batch->expires_at . ' UTC' ) <= time() ) $state='expired'; elseif ( $batch && ( 'active' !== $batch->status || $batch->entitlements_used >= $batch->entitlements_total ) ) $state='exhausted';
		if ( $batch && is_user_logged_in() && 'POST' === $_SERVER['REQUEST_METHOD'] && isset( $_POST['ate_redeem'] ) ) { if ( ! isset( $_POST['_ate_nonce'] ) || ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['_ate_nonce'] ) ), 'ate_redeem_' . $batch->id ) ) $state='failed'; else $state=$this->service->redeem( $token, get_current_user_id() ); }
		status_header( 'invalid' === $state ? 404 : 200 ); nocache_headers(); get_header(); echo '<main class="ate-redemption" style="max-width:760px;margin:3rem auto;padding:1.5rem">';
		if ( ! $batch ) echo '<h1>' . esc_html__( 'Training invitation', 'aspen-training-entitlements' ) . '</h1><p>' . esc_html( $this->state_message( 'invalid' ) ) . '</p>';
		else { $title=get_the_title( $batch->course_id ); echo '<h1>' . esc_html( $title ) . '</h1><p>' . esc_html( sprintf( __( 'Invitation expires %s.', 'aspen-training-entitlements' ), wp_date( get_option( 'date_format' ) . ' ' . get_option( 'time_format' ), strtotime( $batch->expires_at . ' UTC' ) ) ) ) . '</p>'; if ( $state ) echo '<div class="woocommerce-' . ( 'success'===$state ? 'message' : 'info' ) . '">' . esc_html( $this->state_message( $state ) ) . '</div>'; if ( in_array( $state, array( 'success','already_redeemed','already_enrolled' ), true ) ) echo '<p><a class="button" href="' . esc_url( $this->lifter->url( $batch->course_id ) ) . '">' . esc_html__( 'Access course', 'aspen-training-entitlements' ) . '</a></p>'; elseif ( ! is_user_logged_in() ) { $return=$this->tokens->url( $token ); echo '<p>' . esc_html__( 'Log in or create an account to redeem one enrollment.', 'aspen-training-entitlements' ) . '</p><p><a class="button" href="' . esc_url( wp_login_url( $return ) ) . '">' . esc_html__( 'Log in', 'aspen-training-entitlements' ) . '</a> <a class="button" href="' . esc_url( add_query_arg( 'redirect_to', rawurlencode( $return ), wp_registration_url() ) ) . '">' . esc_html__( 'Create account', 'aspen-training-entitlements' ) . '</a></p>'; } elseif ( ! $state ) { echo '<form method="post">'; wp_nonce_field( 'ate_redeem_' . $batch->id, '_ate_nonce' ); echo '<button class="button" name="ate_redeem" value="1">' . esc_html__( 'Redeem enrollment', 'aspen-training-entitlements' ) . '</button></form>'; } }
		echo '</main>'; get_footer(); exit;
	}
	public function account() { $batches=$this->batches->for_customer( get_current_user_id() ); echo '<h2>' . esc_html__( 'Training Enrollments', 'aspen-training-entitlements' ) . '</h2>'; if ( ! $batches ) { echo '<p>' . esc_html__( 'No entitlement batches found.', 'aspen-training-entitlements' ) . '</p>'; return; } foreach ( $batches as $batch ) { $expired=strtotime( $batch->expires_at . ' UTC' ) <= time(); $status=$expired && 'active'===$batch->status ? 'expired' : $batch->status; $order=wc_get_order( $batch->order_id ); echo '<section class="ate-batch" style="border:1px solid #ddd;padding:1rem;margin-bottom:1rem"><h3>' . esc_html( get_the_title( $batch->course_id ) ) . '</h3><p>' . esc_html( sprintf( __( 'Order #%1$s · Purchased %2$s · Expires %3$s', 'aspen-training-entitlements' ), $order ? $order->get_order_number() : $batch->order_id, wp_date( get_option( 'date_format' ), strtotime( $batch->created_at . ' UTC' ) ), wp_date( get_option( 'date_format' ), strtotime( $batch->expires_at . ' UTC' ) ) ) ) . '</p><p><strong>' . esc_html( sprintf( __( '%1$d of %2$d enrollments remaining', 'aspen-training-entitlements' ), max( 0, $batch->entitlements_total-$batch->entitlements_used ), $batch->entitlements_total ) ) . '</strong> (' . esc_html( ucfirst( $status ) ) . ')</p>'; if ( 'active'===$status && $batch->entitlements_used<$batch->entitlements_total ) { $item=$order ? $order->get_item( $batch->order_item_id ) : null; $token=$item ? $item->get_meta( '_ate_redemption_token', true ) : ''; if ( $token ) echo '<p><input readonly value="' . esc_attr( $this->tokens->url( $token ) ) . '" style="width:70%"> <button type="button" class="button ate-copy">' . esc_html__( 'Copy Link', 'aspen-training-entitlements' ) . '</button></p>'; } $rows=$this->redemptions->completed_for_batch( $batch->id ); echo '<table><thead><tr><th>' . esc_html__( 'Trainee', 'aspen-training-entitlements' ) . '</th><th>' . esc_html__( 'Redeemed', 'aspen-training-entitlements' ) . '</th></tr></thead><tbody>'; foreach ( $rows as $row ) { $name=trim( $row->first_name_snapshot . ' ' . $row->last_name_snapshot ); echo '<tr><td>' . esc_html( $name ?: __( 'Trainee', 'aspen-training-entitlements' ) ) . '</td><td>' . esc_html( wp_date( get_option( 'date_format' ), strtotime( $row->redeemed_at . ' UTC' ) ) ) . '</td></tr>'; } echo '</tbody></table></section>'; } echo '<script>document.querySelectorAll(".ate-copy").forEach(b=>b.addEventListener("click",()=>navigator.clipboard.writeText(b.previousElementSibling.value)));</script>'; }
}
